version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000"  # Expose port 3000 of the container to port 3000 of the host machine

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8080"  # Expose port 80 for Nginx

